server {
    listen 80;
    listen [::]:80;
    server_name localhost 127.0.0.1;
    root /var/www/html/bagisto/local/default/public;

    include /etc/nginx/snippets/bagisto.conf;
}

server {
    listen 80;
    listen [::]:80;
    server_name bagisto-2-3-x-dev.test;
    root /var/www/html/bagisto/local/2-3-x-dev/public;

    include /etc/nginx/snippets/bagisto.conf;
}

server {
    listen 80;
    listen [::]:80;
    server_name bagisto-2-4-x-dev.test;
    root /var/www/html/bagisto/local/2-4-x-dev/public;

    include /etc/nginx/snippets/bagisto.conf;
}

server {
    listen 80;
    listen [::]:80;
    server_name bagisto-2-5-x-dev.test;
    root /var/www/html/bagisto/local/2-5-x-dev/public;

    include /etc/nginx/snippets/bagisto.conf;
}

server {
    listen 80;
    listen [::]:80;
    server_name bagisto-multi-channel.test c1.bagisto-multi-channel.test c2.bagisto-multi-channel.test;
    root /var/www/html/bagisto/local/multi-channel/public;

    include /etc/nginx/snippets/bagisto.conf;
}

server {
    listen 80;
    listen [::]:80;
    server_name bagisto-module-1.test;
    root /var/www/html/bagisto/local/module-1/public;

    include /etc/nginx/snippets/bagisto.conf;
}

server {
    listen 80;
    listen [::]:80;
    server_name bagisto-module-2.test;
    root /var/www/html/bagisto/local/module-2/public;

    include /etc/nginx/snippets/bagisto.conf;
}
