server {
    listen 80;
    listen [::]:80;
    server_name 192.168.15.114;
    root /var/www/html/bagisto/shared/default/public;

    include /etc/nginx/snippets/bagisto.conf;
}

server {
    listen 80;
    listen [::]:80;
    server_name devansh.webkul.in;
    root /var/www/html/bagisto/shared/devansh/public;

    include /etc/nginx/snippets/bagisto.conf;
}

server {
    listen 80;
    listen [::]:80;
    server_name devansh-benchmarking.webkul.in;
    root /var/www/html/bagisto/shared/devansh-benchmarking/public;

    include /etc/nginx/snippets/bagisto.conf;
}
